(cl:defpackage gazebo_sfm_plugin-msg
  (:use )
  (:export
   "<TASK>"
   "TASK"
   "<TASKASSIGNMENTACTION>"
   "TASKASSIGNMENTACTION"
   "<TASKASSIGNMENTACTIONFEEDBACK>"
   "TASKASSIGNMENTACTIONFEEDBACK"
   "<TASKASSIGNMENTACTIONGOAL>"
   "TASKASSIGNMENTACTIONGOAL"
   "<TASKASSIGNMENTACTIONRESULT>"
   "TASKASSIGNMENTACTIONRESULT"
   "<TASKASSIGNMENTFEEDBACK>"
   "TASKASSIGNMENTFEEDBACK"
   "<TASKASSIGNMENTGOAL>"
   "TASKASSIGNMENTGOAL"
   "<TASKASSIGNMENTRESULT>"
   "TASKASSIGNMENTRESULT"
  ))

