; Auto-generated. Do not edit!


(cl:in-package gazebo_sfm_plugin-msg)


;//! \htmlinclude TaskAssignmentFeedback.msg.html

(cl:defclass <TaskAssignmentFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass TaskAssignmentFeedback (<TaskAssignmentFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TaskAssignmentFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TaskAssignmentFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gazebo_sfm_plugin-msg:<TaskAssignmentFeedback> is deprecated: use gazebo_sfm_plugin-msg:TaskAssignmentFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <TaskAssignmentFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gazebo_sfm_plugin-msg:percent_complete-val is deprecated.  Use gazebo_sfm_plugin-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TaskAssignmentFeedback>) ostream)
  "Serializes a message object of type '<TaskAssignmentFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TaskAssignmentFeedback>) istream)
  "Deserializes a message object of type '<TaskAssignmentFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TaskAssignmentFeedback>)))
  "Returns string type for a message object of type '<TaskAssignmentFeedback>"
  "gazebo_sfm_plugin/TaskAssignmentFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TaskAssignmentFeedback)))
  "Returns string type for a message object of type 'TaskAssignmentFeedback"
  "gazebo_sfm_plugin/TaskAssignmentFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TaskAssignmentFeedback>)))
  "Returns md5sum for a message object of type '<TaskAssignmentFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TaskAssignmentFeedback)))
  "Returns md5sum for a message object of type 'TaskAssignmentFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TaskAssignmentFeedback>)))
  "Returns full string definition for message of type '<TaskAssignmentFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TaskAssignmentFeedback)))
  "Returns full string definition for message of type 'TaskAssignmentFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TaskAssignmentFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TaskAssignmentFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TaskAssignmentFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
