# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gazebo_sfm_plugin/Task.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Task(genpy.Message):
  _md5sum = "f3b3fd965b6c18a7c7b49995790c231c"
  _type = "gazebo_sfm_plugin/Task"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string name
float64 x_humans
float64 y_humans
float64 x_robots
float64 y_robots
bool for_humans
bool for_robots"""
  __slots__ = ['name','x_humans','y_humans','x_robots','y_robots','for_humans','for_robots']
  _slot_types = ['string','float64','float64','float64','float64','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,x_humans,y_humans,x_robots,y_robots,for_humans,for_robots

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Task, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = ''
      if self.x_humans is None:
        self.x_humans = 0.
      if self.y_humans is None:
        self.y_humans = 0.
      if self.x_robots is None:
        self.x_robots = 0.
      if self.y_robots is None:
        self.y_robots = 0.
      if self.for_humans is None:
        self.for_humans = False
      if self.for_robots is None:
        self.for_robots = False
    else:
      self.name = ''
      self.x_humans = 0.
      self.y_humans = 0.
      self.x_robots = 0.
      self.y_robots = 0.
      self.for_humans = False
      self.for_robots = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4d2B().pack(_x.x_humans, _x.y_humans, _x.x_robots, _x.y_robots, _x.for_humans, _x.for_robots))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.x_humans, _x.y_humans, _x.x_robots, _x.y_robots, _x.for_humans, _x.for_robots,) = _get_struct_4d2B().unpack(str[start:end])
      self.for_humans = bool(self.for_humans)
      self.for_robots = bool(self.for_robots)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4d2B().pack(_x.x_humans, _x.y_humans, _x.x_robots, _x.y_robots, _x.for_humans, _x.for_robots))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.x_humans, _x.y_humans, _x.x_robots, _x.y_robots, _x.for_humans, _x.for_robots,) = _get_struct_4d2B().unpack(str[start:end])
      self.for_humans = bool(self.for_humans)
      self.for_robots = bool(self.for_robots)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d2B = None
def _get_struct_4d2B():
    global _struct_4d2B
    if _struct_4d2B is None:
        _struct_4d2B = struct.Struct("<4d2B")
    return _struct_4d2B
