(cl:defpackage gazebo_sfm_plugin-srv
  (:use )
  (:export
   "LOADTASKS"
   "<LOADTASKS-REQUEST>"
   "LOADTASKS-REQUEST"
   "<LOADTASKS-RESPONSE>"
   "LOADTASKS-RESPONSE"
   "RETURN_HOME"
   "<RETURN_HOME-REQUEST>"
   "RETURN_HOME-REQUEST"
   "<RETURN_HOME-RESPONSE>"
   "RETURN_HOME-RESPONSE"
   "UPDATE_WAYPOINT"
   "<UPDATE_WAYPOINT-REQUEST>"
   "UPDATE_WAYPOINT-REQUEST"
   "<UPDATE_WAYPOINT-RESPONSE>"
   "UPDATE_WAYPOINT-RESPONSE"
  ))

