// Generated by gencpp from file gazebo_sfm_plugin/AssignTaskRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_ASSIGNTASKREQUEST_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_ASSIGNTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace gazebo_sfm_plugin
{
template <class ContainerAllocator>
struct AssignTaskRequest_
{
  typedef AssignTaskRequest_<ContainerAllocator> Type;

  AssignTaskRequest_()
    : waypoints()  {
    }
  AssignTaskRequest_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AssignTaskRequest_

typedef ::gazebo_sfm_plugin::AssignTaskRequest_<std::allocator<void> > AssignTaskRequest;

typedef boost::shared_ptr< ::gazebo_sfm_plugin::AssignTaskRequest > AssignTaskRequestPtr;
typedef boost::shared_ptr< ::gazebo_sfm_plugin::AssignTaskRequest const> AssignTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator1> & lhs, const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator1> & lhs, const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_sfm_plugin

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0511c019d3d3f0edeb56aaf3709c8aea";
  }

  static const char* value(const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0511c019d3d3f0edULL;
  static const uint64_t static_value2 = 0xeb56aaf3709c8aeaULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_sfm_plugin/AssignTaskRequest";
  }

  static const char* value(const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AssignTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_sfm_plugin::AssignTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_ASSIGNTASKREQUEST_H
