// Generated by gencpp from file gazebo_sfm_plugin/AssignTask.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_ASSIGNTASK_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_ASSIGNTASK_H

#include <ros/service_traits.h>


#include <gazebo_sfm_plugin/AssignTaskRequest.h>
#include <gazebo_sfm_plugin/AssignTaskResponse.h>


namespace gazebo_sfm_plugin
{

struct AssignTask
{

typedef AssignTaskRequest Request;
typedef AssignTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssignTask
} // namespace gazebo_sfm_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_sfm_plugin::AssignTask > {
  static const char* value()
  {
    return "e65fdf0b922727bc18f1f1772a8f5a15";
  }

  static const char* value(const ::gazebo_sfm_plugin::AssignTask&) { return value(); }
};

template<>
struct DataType< ::gazebo_sfm_plugin::AssignTask > {
  static const char* value()
  {
    return "gazebo_sfm_plugin/AssignTask";
  }

  static const char* value(const ::gazebo_sfm_plugin::AssignTask&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_sfm_plugin::AssignTaskRequest> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::AssignTask >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::AssignTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::AssignTask >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::AssignTaskRequest> should match
// service_traits::DataType< ::gazebo_sfm_plugin::AssignTask >
template<>
struct DataType< ::gazebo_sfm_plugin::AssignTaskRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::AssignTask >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_sfm_plugin::AssignTaskResponse> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::AssignTask >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::AssignTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::AssignTask >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::AssignTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::AssignTaskResponse> should match
// service_traits::DataType< ::gazebo_sfm_plugin::AssignTask >
template<>
struct DataType< ::gazebo_sfm_plugin::AssignTaskResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::AssignTask >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::AssignTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_ASSIGNTASK_H
