// Generated by gencpp from file gazebo_sfm_plugin/LoadTasksRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_LOADTASKSREQUEST_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_LOADTASKSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace gazebo_sfm_plugin
{
template <class ContainerAllocator>
struct LoadTasksRequest_
{
  typedef LoadTasksRequest_<ContainerAllocator> Type;

  LoadTasksRequest_()
    : use_file(false)
    , file_path()
    , task_names()
    , positions()
    , target_types()  {
    }
  LoadTasksRequest_(const ContainerAllocator& _alloc)
    : use_file(false)
    , file_path(_alloc)
    , task_names(_alloc)
    , positions(_alloc)
    , target_types(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _use_file_type;
  _use_file_type use_file;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_path_type;
  _file_path_type file_path;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _task_names_type;
  _task_names_type task_names;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _positions_type;
  _positions_type positions;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _target_types_type;
  _target_types_type target_types;





  typedef boost::shared_ptr< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadTasksRequest_

typedef ::gazebo_sfm_plugin::LoadTasksRequest_<std::allocator<void> > LoadTasksRequest;

typedef boost::shared_ptr< ::gazebo_sfm_plugin::LoadTasksRequest > LoadTasksRequestPtr;
typedef boost::shared_ptr< ::gazebo_sfm_plugin::LoadTasksRequest const> LoadTasksRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator1> & lhs, const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator2> & rhs)
{
  return lhs.use_file == rhs.use_file &&
    lhs.file_path == rhs.file_path &&
    lhs.task_names == rhs.task_names &&
    lhs.positions == rhs.positions &&
    lhs.target_types == rhs.target_types;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator1> & lhs, const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_sfm_plugin

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb4b966d20833cec6bbbed888bd4dd89";
  }

  static const char* value(const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb4b966d20833cecULL;
  static const uint64_t static_value2 = 0x6bbbed888bd4dd89ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_sfm_plugin/LoadTasksRequest";
  }

  static const char* value(const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool use_file\n"
"string file_path\n"
"string[] task_names\n"
"geometry_msgs/Point[] positions\n"
"string[] target_types\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.use_file);
      stream.next(m.file_path);
      stream.next(m.task_names);
      stream.next(m.positions);
      stream.next(m.target_types);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadTasksRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_sfm_plugin::LoadTasksRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "use_file: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_file);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_names: ";
    if (v.task_names.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.task_names.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.task_names[i]);
    }
    if (v.task_names.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "positions: ";
    if (v.positions.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.positions[i]);
    }
    if (v.positions.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_types: ";
    if (v.target_types.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_types.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.target_types[i]);
    }
    if (v.target_types.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_LOADTASKSREQUEST_H
