// Generated by gencpp from file gazebo_sfm_plugin/LoadTasks.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_LOADTASKS_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_LOADTASKS_H

#include <ros/service_traits.h>


#include <gazebo_sfm_plugin/LoadTasksRequest.h>
#include <gazebo_sfm_plugin/LoadTasksResponse.h>


namespace gazebo_sfm_plugin
{

struct LoadTasks
{

typedef LoadTasksRequest Request;
typedef LoadTasksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadTasks
} // namespace gazebo_sfm_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_sfm_plugin::LoadTasks > {
  static const char* value()
  {
    return "deda9a7b2b857b0ae878e4665876836b";
  }

  static const char* value(const ::gazebo_sfm_plugin::LoadTasks&) { return value(); }
};

template<>
struct DataType< ::gazebo_sfm_plugin::LoadTasks > {
  static const char* value()
  {
    return "gazebo_sfm_plugin/LoadTasks";
  }

  static const char* value(const ::gazebo_sfm_plugin::LoadTasks&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_sfm_plugin::LoadTasksRequest> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::LoadTasks >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::LoadTasksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::LoadTasks >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::LoadTasksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::LoadTasksRequest> should match
// service_traits::DataType< ::gazebo_sfm_plugin::LoadTasks >
template<>
struct DataType< ::gazebo_sfm_plugin::LoadTasksRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::LoadTasks >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::LoadTasksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_sfm_plugin::LoadTasksResponse> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::LoadTasks >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::LoadTasksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::LoadTasks >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::LoadTasksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::LoadTasksResponse> should match
// service_traits::DataType< ::gazebo_sfm_plugin::LoadTasks >
template<>
struct DataType< ::gazebo_sfm_plugin::LoadTasksResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::LoadTasks >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::LoadTasksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_LOADTASKS_H
