// Generated by gencpp from file gazebo_sfm_plugin/Return_home.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_RETURN_HOME_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_RETURN_HOME_H

#include <ros/service_traits.h>


#include <gazebo_sfm_plugin/Return_homeRequest.h>
#include <gazebo_sfm_plugin/Return_homeResponse.h>


namespace gazebo_sfm_plugin
{

struct Return_home
{

typedef Return_homeRequest Request;
typedef Return_homeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Return_home
} // namespace gazebo_sfm_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_sfm_plugin::Return_home > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::gazebo_sfm_plugin::Return_home&) { return value(); }
};

template<>
struct DataType< ::gazebo_sfm_plugin::Return_home > {
  static const char* value()
  {
    return "gazebo_sfm_plugin/Return_home";
  }

  static const char* value(const ::gazebo_sfm_plugin::Return_home&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_sfm_plugin::Return_homeRequest> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::Return_home >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::Return_homeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::Return_home >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::Return_homeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::Return_homeRequest> should match
// service_traits::DataType< ::gazebo_sfm_plugin::Return_home >
template<>
struct DataType< ::gazebo_sfm_plugin::Return_homeRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::Return_home >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::Return_homeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_sfm_plugin::Return_homeResponse> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::Return_home >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::Return_homeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::Return_home >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::Return_homeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::Return_homeResponse> should match
// service_traits::DataType< ::gazebo_sfm_plugin::Return_home >
template<>
struct DataType< ::gazebo_sfm_plugin::Return_homeResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::Return_home >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::Return_homeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_RETURN_HOME_H
