// Generated by gencpp from file gazebo_sfm_plugin/TaskAssignmentActionGoal.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_TASKASSIGNMENTACTIONGOAL_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_TASKASSIGNMENTACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <gazebo_sfm_plugin/TaskAssignmentGoal.h>

namespace gazebo_sfm_plugin
{
template <class ContainerAllocator>
struct TaskAssignmentActionGoal_
{
  typedef TaskAssignmentActionGoal_<ContainerAllocator> Type;

  TaskAssignmentActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  TaskAssignmentActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::gazebo_sfm_plugin::TaskAssignmentGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TaskAssignmentActionGoal_

typedef ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<std::allocator<void> > TaskAssignmentActionGoal;

typedef boost::shared_ptr< ::gazebo_sfm_plugin::TaskAssignmentActionGoal > TaskAssignmentActionGoalPtr;
typedef boost::shared_ptr< ::gazebo_sfm_plugin::TaskAssignmentActionGoal const> TaskAssignmentActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator1> & lhs, const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator1> & lhs, const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_sfm_plugin

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f5f7caa9296b4f58842906dc69c6016";
  }

  static const char* value(const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f5f7caa9296b4f5ULL;
  static const uint64_t static_value2 = 0x8842906dc69c6016ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_sfm_plugin/TaskAssignmentActionGoal";
  }

  static const char* value(const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"TaskAssignmentGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: gazebo_sfm_plugin/TaskAssignmentGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal definition\n"
"string[] task_names\n"
"geometry_msgs/Point[] positions\n"
"string[] target_types\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskAssignmentActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_sfm_plugin::TaskAssignmentActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::gazebo_sfm_plugin::TaskAssignmentGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_TASKASSIGNMENTACTIONGOAL_H
