// Generated by gencpp from file gazebo_sfm_plugin/TaskAssignmentFeedback.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_TASKASSIGNMENTFEEDBACK_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_TASKASSIGNMENTFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_sfm_plugin
{
template <class ContainerAllocator>
struct TaskAssignmentFeedback_
{
  typedef TaskAssignmentFeedback_<ContainerAllocator> Type;

  TaskAssignmentFeedback_()
    : percent_complete(0.0)  {
    }
  TaskAssignmentFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TaskAssignmentFeedback_

typedef ::gazebo_sfm_plugin::TaskAssignmentFeedback_<std::allocator<void> > TaskAssignmentFeedback;

typedef boost::shared_ptr< ::gazebo_sfm_plugin::TaskAssignmentFeedback > TaskAssignmentFeedbackPtr;
typedef boost::shared_ptr< ::gazebo_sfm_plugin::TaskAssignmentFeedback const> TaskAssignmentFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator1> & lhs, const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator1> & lhs, const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_sfm_plugin

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_sfm_plugin/TaskAssignmentFeedback";
  }

  static const char* value(const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float32 percent_complete\n"
;
  }

  static const char* value(const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskAssignmentFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_sfm_plugin::TaskAssignmentFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_TASKASSIGNMENTFEEDBACK_H
