// Generated by gencpp from file gazebo_sfm_plugin/Update_waypoint.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_UPDATE_WAYPOINT_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_UPDATE_WAYPOINT_H

#include <ros/service_traits.h>


#include <gazebo_sfm_plugin/Update_waypointRequest.h>
#include <gazebo_sfm_plugin/Update_waypointResponse.h>


namespace gazebo_sfm_plugin
{

struct Update_waypoint
{

typedef Update_waypointRequest Request;
typedef Update_waypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Update_waypoint
} // namespace gazebo_sfm_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_sfm_plugin::Update_waypoint > {
  static const char* value()
  {
    return "f5dd19960de228b666941d1879a83836";
  }

  static const char* value(const ::gazebo_sfm_plugin::Update_waypoint&) { return value(); }
};

template<>
struct DataType< ::gazebo_sfm_plugin::Update_waypoint > {
  static const char* value()
  {
    return "gazebo_sfm_plugin/Update_waypoint";
  }

  static const char* value(const ::gazebo_sfm_plugin::Update_waypoint&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_sfm_plugin::Update_waypointRequest> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::Update_waypoint >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::Update_waypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::Update_waypoint >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::Update_waypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::Update_waypointRequest> should match
// service_traits::DataType< ::gazebo_sfm_plugin::Update_waypoint >
template<>
struct DataType< ::gazebo_sfm_plugin::Update_waypointRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::Update_waypoint >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::Update_waypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_sfm_plugin::Update_waypointResponse> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::Update_waypoint >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::Update_waypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::Update_waypoint >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::Update_waypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::Update_waypointResponse> should match
// service_traits::DataType< ::gazebo_sfm_plugin::Update_waypoint >
template<>
struct DataType< ::gazebo_sfm_plugin::Update_waypointResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::Update_waypoint >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::Update_waypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_UPDATE_WAYPOINT_H
