// Auto-generated. Do not edit!

// (in-package gazebo_sfm_plugin.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class TaskAssignmentGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.task_names = null;
      this.positions = null;
      this.target_types = null;
    }
    else {
      if (initObj.hasOwnProperty('task_names')) {
        this.task_names = initObj.task_names
      }
      else {
        this.task_names = [];
      }
      if (initObj.hasOwnProperty('positions')) {
        this.positions = initObj.positions
      }
      else {
        this.positions = [];
      }
      if (initObj.hasOwnProperty('target_types')) {
        this.target_types = initObj.target_types
      }
      else {
        this.target_types = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TaskAssignmentGoal
    // Serialize message field [task_names]
    bufferOffset = _arraySerializer.string(obj.task_names, buffer, bufferOffset, null);
    // Serialize message field [positions]
    // Serialize the length for message field [positions]
    bufferOffset = _serializer.uint32(obj.positions.length, buffer, bufferOffset);
    obj.positions.forEach((val) => {
      bufferOffset = geometry_msgs.msg.Point.serialize(val, buffer, bufferOffset);
    });
    // Serialize message field [target_types]
    bufferOffset = _arraySerializer.string(obj.target_types, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TaskAssignmentGoal
    let len;
    let data = new TaskAssignmentGoal(null);
    // Deserialize message field [task_names]
    data.task_names = _arrayDeserializer.string(buffer, bufferOffset, null)
    // Deserialize message field [positions]
    // Deserialize array length for message field [positions]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.positions = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.positions[i] = geometry_msgs.msg.Point.deserialize(buffer, bufferOffset)
    }
    // Deserialize message field [target_types]
    data.target_types = _arrayDeserializer.string(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    object.task_names.forEach((val) => {
      length += 4 + _getByteLength(val);
    });
    length += 24 * object.positions.length;
    object.target_types.forEach((val) => {
      length += 4 + _getByteLength(val);
    });
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'gazebo_sfm_plugin/TaskAssignmentGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9bcdd9e4ed3cb46133c77abe8391c30a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal definition
    string[] task_names
    geometry_msgs/Point[] positions
    string[] target_types
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TaskAssignmentGoal(null);
    if (msg.task_names !== undefined) {
      resolved.task_names = msg.task_names;
    }
    else {
      resolved.task_names = []
    }

    if (msg.positions !== undefined) {
      resolved.positions = new Array(msg.positions.length);
      for (let i = 0; i < resolved.positions.length; ++i) {
        resolved.positions[i] = geometry_msgs.msg.Point.Resolve(msg.positions[i]);
      }
    }
    else {
      resolved.positions = []
    }

    if (msg.target_types !== undefined) {
      resolved.target_types = msg.target_types;
    }
    else {
      resolved.target_types = []
    }

    return resolved;
    }
};

module.exports = TaskAssignmentGoal;
